### ISSUE TITLE
Cannot install drawio_network_plot with pip

### ISSUE THREAD

**Issue by fhg-isi** [amrelhusseiny/drawio_network_plot#6]
`pip install drawio_network_plot
Collecting drawio_network_plot
  Using cached drawio_network_plot-0.0.02.Beta.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\eis\AppData\Local\Temp\PyCharmPortableTemp\pip-install-nhz68lt1\drawio-network-plot_3827cbdc198749b5bbcd4f1b528e4b5d\setup.py", line 12, in <module>
          setup(
        File "C:\python_env\App\WinPython\python-3.12.4.amd64\Lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\python_env\App\WinPython\python-3.12.4.amd64\Lib\site-packages\setuptools\_distutils\core.py", line 145, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "C:\python_env\App\WinPython\python-3.12.4.amd64\Lib\site-packages\setuptools\dist.py", line 330, in __init__
          self.metadata.version = self._normalize_version(self.metadata.version)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\python_env\App\WinPython\python-3.12.4.amd64\Lib\site-packages\setuptools\dist.py", line 366, in _normalize_version
          normalized = str(Version(version))
                           ^^^^^^^^^^^^^^^^
        File "C:\python_env\App\WinPython\python-3.12.4.amd64\Lib\site-packages\packaging\version.py", line 202, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      packaging.version.InvalidVersion: Invalid version: '0.0.02 Beta'`

**Comment by andycoco** [comment]
I encounter the same issue,hummm..
